function manual_marker_pad()
    %% 1. Configure Path and Initialize LSL
    % CHANGE THIS PATH to match your actual liblsl-Matlab folder location
    lsl_path = 'C:\path\to\liblsl-Matlab'; 
    
    if ~exist('lsl_loadlib', 'file')
        addpath(genpath(lsl_path));
    end
    
    try
        lib = lsl_loadlib();
    catch
        error('Could not load LSL library. Please verify your lsl_path is correct.');
    end

    %% 2. Create the LSL Marker Stream
    info = lsl_streaminfo(lib, 'GuiMarkers', 'Markers', 1, 0, 'cf_string', 'gui_marker_pad_999');
    outlet = lsl_outlet(info);
    disp('LSL GUI Marker Stream is online with customized buttons!');

    %% 3. Create the Graphic Window (GUI)
    % Expanded window to accommodate 9 buttons comfortably
    fig = figure('Name', 'LSL Marker Dashboard', ...
                 'MenuBar', 'none', ...
                 'NumberTitle', 'off', ...
                 'Position',); % [X, Y, Width, Height]

    %% Group 1: Trial Controls (Green Block)
    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '▶ Trial Start', ...
              'Position',, 'FontSize', 11, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.75, 0.95, 0.75], ...
              'Callback', @(~,~) send_marker(outlet, 'Trial Start'));

    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '■ Trial End', ...
              'Position',, 'FontSize', 11, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.95, 0.75, 0.75], ...
              'Callback', @(~,~) send_marker(outlet, 'Trial End'));

    %% Group 2: Eye States & Tasks (Blue Block)
    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '👁 Eyes Open', ...
              'Position',, 'FontSize', 11, ...
              'BackgroundColor', [0.8, 0.9, 1.0], ...
              'Callback', @(~,~) send_marker(outlet, 'Eyes Open'));

    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '🔒 Eyes Closed', ...
              'Position',, 'FontSize', 11, ...
              'BackgroundColor', [0.7, 0.8, 0.95], ...
              'Callback', @(~,~) send_marker(outlet, 'Eyes Closed'));

    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '〰 Blinking', ...
              'Position',, 'FontSize', 11, ...
              'BackgroundColor', [0.85, 0.92, 1.0], ...
              'Callback', @(~,~) send_marker(outlet, 'Blinking'));

    %% Group 3: Artifacts / Muscle Noise (Orange Block)
    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '😬 Jaw Clench', ...
              'Position',, 'FontSize', 11, ...
              'BackgroundColor', [1.0, 0.85, 0.6], ...
              'Callback', @(~,~) send_marker(outlet, 'Jaw Clench'));

    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '💬 Talking', ...
              'Position',, 'FontSize', 11, ...
              'BackgroundColor', [1.0, 0.9, 0.7], ...
              'Callback', @(~,~) send_marker(outlet, 'Talking'));

    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '⚠ Bad/Movement', ...
              'Position',, 'FontSize', 11, 'FontWeight', 'bold', ...
              'BackgroundColor', [1.0, 0.7, 0.6], ...
              'Callback', @(~,~) send_marker(outlet, 'Bad/Movement'));

    %% Group 4: Motor Tasks (Purple Block)
    uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', '🚶 One Leg Step Initiation', ...
              'Position',, 'FontSize', 11, 'FontWeight', 'bold', ...
              'BackgroundColor', [0.9, 0.8, 0.95], ...
              'Callback', @(~,~) send_marker(outlet, 'One Leg Step Initiation'));
end

%% Helper Function to Push the Marker Instantly
function send_marker(outlet, marker_text)
    outlet.push_sample({marker_text});
    fprintf('[%s] Sent marker: "%s"\n', datestr(now, 'HH:MM:SS.FFF'), marker_text);
end
