%% mvc_marker_gui
% Creates a MATLAB graphical interface for broadcasting impedance, MVC,
% rest, and muscle-label markers through Lab Streaming Layer (LSL) during
% data collection.
%
% This script creates the MVC-related marker stream:
%   Name:      MVCMarkers
%   Type:      Markers
%   Channels:  1
%   Format:    cf_string
%   Source ID: mvc_marker_gui_001
%
% A separate marker script may use a similar interface structure while
% broadcasting a different set of markers through its own unique LSL
% stream.
%
% Requirements:
%   - MATLAB
%   - A compatible version of liblsl-Matlab
%   - LabRecorder or another compatible LSL recording application
%
% Before use:
%   - Set lslPath below if liblsl-Matlab is not already on the MATLAB path.
%   - Confirm that MVCMarkers appears in LabRecorder.
%   - Test each button before beginning a recording session.
%
% Usage:
%   Run this script from the MATLAB Command Window or Editor. Pressing a
%   button sends the corresponding marker immediately through LSL.

clear;
clc;

%% User Settings

% Set this to the local liblsl-Matlab folder.
% This setting is only used when lsl_loadlib is not already available on
% the MATLAB path.
%
% Example:
% lslPath = 'C:\Users\YourName\Downloads\liblsl-Matlab';
lslPath = 'C:\path\to\liblsl-Matlab';

%% Load the LSL Library

% Add liblsl-Matlab and its subfolders to the current MATLAB path when the
% required LSL function is not already available.
if ~exist('lsl_loadlib', 'file')
    if ~isfolder(lslPath)
        error([ ...
            'liblsl-Matlab was not found on the MATLAB path, and ' ...
            'lslPath does not point to a valid folder. Update lslPath ' ...
            'in the User Settings section.']);
    end

    addpath(genpath(lslPath));
end

try
    lib = lsl_loadlib();
catch
    error([ ...
        'CRITICAL ERROR: Could not load the LSL library. Verify the ' ...
        'liblsl-Matlab installation and the lslPath setting.']);
end

%% Create the MVC Marker Stream

% The stream name and source ID distinguish this interface from other
% marker interfaces used during the same recording session.
info = lsl_streaminfo( ...
    lib, ...
    'MVCMarkers', ...
    'Markers', ...
    1, ...
    0, ...
    'cf_string', ...
    'mvc_marker_gui_001');

outlet = lsl_outlet(info);

clc;

disp('======================================================');
disp(' SUCCESS: MVC marker LSL stream is broadcasting!');
disp(' -> Open LabRecorder, select Refresh, and check "MVCMarkers".');
disp('======================================================');

%% Configure the Interface

winWidth = 320;
winHeight = 620;

fig = figure( ...
    'Name', 'MVC Marker Dashboard', ...
    'MenuBar', 'none', ...
    'NumberTitle', 'off');

set(fig, 'Position', [100, 100, winWidth, winHeight]);

% Shared button appearance.
grayColor = [0.92, 0.92, 0.92];
textColor = [0, 0, 0];

% Shared button dimensions and spacing.
buttonWidth = 280;
buttonHeight = 40;
startX = 20;
startY = 550;
buttonSpacing = 50;
sectionGap = 20;

%% Create the Marker Buttons

% Button 1: Impedance Test Start
button1 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Impedance Test Start', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Impedance Test Start'));

set(button1, ...
    'Position', [startX, startY, buttonWidth, buttonHeight]);

% Button 2: Impedance Test End
button2 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Impedance Test End', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Impedance Test End'));

set(button2, ...
    'Position', ...
    [startX, startY - 1 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 3: MVC Start
button3 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'MVC Start', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'MVC Start'));

set(button3, ...
    'Position', ...
    [startX, startY - 2 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 4: MVC End
button4 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'MVC End', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'MVC End'));

set(button4, ...
    'Position', ...
    [startX, startY - 3 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 5: Rest Start
button5 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Rest Start', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Rest Start'));

set(button5, ...
    'Position', ...
    [startX, startY - 4 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 6: Rest End
button6 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Rest End', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Rest End'));

set(button6, ...
    'Position', ...
    [startX, startY - 5 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 7: TA
button7 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'TA', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'TA'));

set(button7, ...
    'Position', ...
    [startX, startY - 6 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 8: PL
button8 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'PL', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'PL'));

set(button8, ...
    'Position', ...
    [startX, startY - 7 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 9: GM
button9 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'GM', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'GM'));

set(button9, ...
    'Position', ...
    [startX, startY - 8 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

% Button 10: GL
button10 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'GL', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'GL'));

set(button10, ...
    'Position', ...
    [startX, startY - 9 * buttonSpacing - sectionGap, ...
     buttonWidth, buttonHeight]);

%% Local Function

function send_live_marker(outlet, markerText)
%SEND_LIVE_MARKER Send one string marker through LSL and print confirmation.

    outlet.push_sample({markerText});

    timestamp = char(datetime("now", "Format", "HH:mm:ss.SSS"));

    fprintf( ...
        '[%s] LSL Broadcast -> Recorded MVC Event: "%s"\n', ...
        timestamp, ...
        markerText);
end
