%% task_marker_gui
% Creates a MATLAB graphical interface for broadcasting task and artifact
% markers through Lab Streaming Layer (LSL) during multimodal data
% collection.
%
% This script creates the task-related marker stream:
%   Name:      TaskMarkers
%   Type:      Markers
%   Channels:  1
%   Format:    cf_string
%   Source ID: task_marker_gui_001
%
% A separate marker script may use a similar interface structure while
% broadcasting a different set of markers through its own unique LSL
% stream.
%
% Requirements:
%   - MATLAB
%   - A compatible version of liblsl-Matlab
%   - LabRecorder or another compatible LSL recording application
%
% Before use:
%   - Set lslPath below if liblsl-Matlab is not already on the MATLAB path.
%   - Confirm that TaskMarkers appears in LabRecorder.
%   - Test each button before beginning a recording session.
%
% Usage:
%   Run this script from the MATLAB Command Window or Editor. Pressing a
%   button sends the corresponding marker immediately through LSL.

clear;
clc;

%% User Settings

% Set this to the local liblsl-Matlab folder.
% This setting is only used when lsl_loadlib is not already available on
% the MATLAB path.
%
% Example:
% lslPath = 'C:\Users\YourName\Downloads\liblsl-Matlab';
lslPath = 'C:\path\to\liblsl-Matlab';

%% Load the LSL Library

% Add liblsl-Matlab and its subfolders to the current MATLAB path when the
% required LSL function is not already available.
if ~exist('lsl_loadlib', 'file')
    if ~isfolder(lslPath)
        error([ ...
            'liblsl-Matlab was not found on the MATLAB path, and ' ...
            'lslPath does not point to a valid folder. Update lslPath ' ...
            'in the User Settings section.']);
    end

    addpath(genpath(lslPath));
end

try
    lib = lsl_loadlib();
catch
    error([ ...
        'CRITICAL ERROR: Could not load the LSL library. Verify the ' ...
        'liblsl-Matlab installation and the lslPath setting.']);
end

%% Create the Task Marker Stream

% The stream name and source ID distinguish this interface from other
% marker interfaces used during the same recording session.
info = lsl_streaminfo( ...
    lib, ...
    'TaskMarkers', ...
    'Markers', ...
    1, ...
    0, ...
    'cf_string', ...
    'task_marker_gui_001');

outlet = lsl_outlet(info);

clc;

disp('======================================================');
disp(' SUCCESS: Task marker LSL stream is broadcasting!');
disp(' -> Open LabRecorder, select Refresh, and check "TaskMarkers".');
disp('======================================================');

%% Configure the Interface

winWidth = 320;
winHeight = 600;

fig = figure( ...
    'Name', 'Task Marker Dashboard', ...
    'MenuBar', 'none', ...
    'NumberTitle', 'off');

set(fig, 'Position', [100, 100, winWidth, winHeight]);

% Shared button appearance.
grayColor = [0.92, 0.92, 0.92];
textColor = [0, 0, 0];

% Shared button dimensions and spacing.
buttonWidth = 280;
buttonHeight = 40;
startX = 20;
startY = 540;
buttonSpacing = 50;

%% Create the Marker Buttons

% Button 1: Trial Start
button1 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Trial Start', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Trial Start'));

set(button1, ...
    'Position', [startX, startY, buttonWidth, buttonHeight]);

% Button 2: Trial End
button2 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Trial End', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Trial End'));

set(button2, ...
    'Position', ...
    [startX, startY - 1 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 3: Blinking
button3 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Blinking', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Blinking'));

set(button3, ...
    'Position', ...
    [startX, startY - 2 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 4: Jaw Clench
button4 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Jaw Clench', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Jaw Clench'));

set(button4, ...
    'Position', ...
    [startX, startY - 3 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 5: Talking
button5 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Talking', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Talking'));

set(button5, ...
    'Position', ...
    [startX, startY - 4 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 6: Bad Movement
button6 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Bad Movement', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Bad Movement'));

set(button6, ...
    'Position', ...
    [startX, startY - 5 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 7: Eyes Open
button7 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Eyes Open', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Eyes Open'));

set(button7, ...
    'Position', ...
    [startX, startY - 6 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 8: Eyes Closed
button8 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Eyes Closed', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Eyes Closed'));

set(button8, ...
    'Position', ...
    [startX, startY - 7 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 9: One Leg
button9 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'One Leg', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'One Leg'));

set(button9, ...
    'Position', ...
    [startX, startY - 8 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 10: Dual Task
button10 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Dual Task', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Dual Task'));

set(button10, ...
    'Position', ...
    [startX, startY - 9 * buttonSpacing, buttonWidth, buttonHeight]);

% Button 11: Step Initiation
button11 = uicontrol( ...
    'Parent', fig, ...
    'Style', 'pushbutton', ...
    'String', 'Step Initiation', ...
    'FontSize', 11, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', grayColor, ...
    'ForegroundColor', textColor, ...
    'Callback', @(~, ~) send_live_marker(outlet, 'Step Initiation'));

set(button11, ...
    'Position', ...
    [startX, startY - 10 * buttonSpacing, buttonWidth, buttonHeight]);

%% Local Function

function send_live_marker(outlet, markerText)
%SEND_LIVE_MARKER Send one string marker through LSL and print confirmation.

    outlet.push_sample({markerText});

    fprintf( ...
        '[%s] LSL Broadcast -> Recorded Event: "%s"\n', ...
        datestr(now, 'HH:MM:SS.FFF'), ...
        markerText);
end
